### PR TITLE
Update 99-misc-release-set-version.patch

### PR DESCRIPTION
**Pull request by adamhassel**
Update patch to latest upstream release

### CODE REVIEW

**Comment by adamhassel** [comment]
Nah, it'll have to be somewhere else...

**Comment by Betterbird** [comment]
Thanks for your interest. We will be releasing BB 91.0.3-bb12 as soon as TB is ready with 91.0.3. Or, if we have more fixes we what to ship before, we'll do a 91.0.2-bb12.

**Comment by adamhassel** [comment]
> Thanks for your interest. We will be releasing BB 91.0.3-bb12 as soon as TB is ready with 91.0.3 (looks like they are getting ready at time of writing).

Yeah, I was only making the PR because the release hg repo at Mozilla had (has) 9.0.3 as a version string, which caused that BB patch to fail...

**Comment by Betterbird** [comment]
All good now, I'm preparing BB 91.0.3-bb12 right now with fresh cherry-picked extra patches. Are you using Achim's ansible build? It has two problems on Linux (doesn't install python3-pip, "ac_add_options --disable-maintenance-service" not working on Linux). Anyway, we can talk via e-mail.

**Pull request closed without merging**
