### PR TITLE
Dutch localization

### PR DESCRIPTION
**Pull request by oeekker**

### CODE REVIEW

**Comment by Betterbird** [comment]
Very nice, many thanks. The "Decrypt to Folder". Enigmail has:
https://gitlab.com/enigmail/enigmail/-/blob/master/lang/nl/enigmail.dtd#L115
"Ontcijferen naar map"
Is that better?

And just for your info: The %icv% can be dropped, since the Dutch strings are pure ASCII (unless I missed something). I can fix both myself.

**Comment by oeekker** [comment]
"Ontcijferen" isn't better than "Ontsleutelen", except maybe for consistency, but i think the string in Enigmail should be changed in that case.
"Ontcijferen" is the translation of "Decipher", while "Ontsleutelen" is the translation of "Decrypt".
Unfortunately neither in the original language nor in the translation is either of both terms used consistently...

**Comment by Betterbird** [comment]
OK, what about the preposition "in" vs. "naar"? "Naar" sounds like a German "nach", so that's closer to "to" than "in". The function takes the messages and stores the decrypted copy into another folder, like a "copy to" function, so the notion of direction is somewhat important.

**Comment by oeekker** [comment]
Hmz, that one is a bit arbitrary also. The decrypted copies are stored *in* the folder, that's why I used "in", but "naar/nach" is also possible,

**Comment by Betterbird** [comment]
Thanks, I think I'll go with "naar".

BTW, "nach" wouldn't work in German, it needs to be "in". But the preposition "in" can go with Dativ or Akkusativ, the latter implying movement or direction. "in (den) Ordner" would imply Akkusativ, since "im/in dem Ordner" is Dativ. The joy of localisation.

**Pull request merged**
