### PR TITLE
Use pkg-config to detect libdbusmenu directories

### PR DESCRIPTION
**Pull request by SuperSandro2000**
I am packaging betterbird for NixOS and that has no /usr/ directory.

### CODE REVIEW

**Comment by Betterbird** [comment]
Thanks, but that patches the Makefile for the sample program. How about this:
https://github.com/Betterbird/thunderbird-patches/blob/dfd8bbf089a46d2e1e9ccd6ccab88aa21a24775e/102/features/12-feature-linux-systray.patch#L4691
That's in the moz.build file: third_party/moz.build b/third_party/moz.build

**Comment by Betterbird** [comment]
Please note https://github.com/Betterbird/thunderbird-patches/commit/4f65bce0d4e224f1d7448a7f5fa1d8b63773dd21

**Comment by SuperSandro2000** [comment]
I saw that already but I don't know how moz.build files work, so I just patched that in the build script.

**Comment by Betterbird** [comment]
Hmm, the Mozilla build system is Python based. We don't have exact knowledge, so we just hacked those include flags into the moz.build file. Maybe some of this
https://searchfox.org/mozilla-central/search?q=pkg-config&path=&case=false&regexp=false
could be an inspiration of who to do it properly.

**Comment by SuperSandro2000** [comment]
The python code used in moz.build is very restricted and can't exec pkg-config and I am not motivated enough to properly fix it. Patching is fine for me now.

**Pull request merged**
