### PR TITLE
Update zh-CN translation

### PR DESCRIPTION
**Pull request by scruel**

### CODE REVIEW

**Comment by Betterbird** [comment]
Thanks for doing this. This block is not required since the strings are already correct in the TB language pack:
```
sed -i -e 's/return-receipt-checkbox/return-receipt-checkbox-control/'       localization\zh-CN\messenger\preferences\receipts.ftl
sed -i -e 's/receipt-leave-radio/receipt-leave-radio-control/'               localization\zh-CN\messenger\preferences\receipts.ftl
sed -i -e 's/receipt-move-radio/receipt-move-radio-control/'                 localization\zh-CN\messenger\preferences\receipts.ftl
sed -i -e 's/receipt-return-never-radio/receipt-return-never-radio-control/' localization\zh-CN\messenger\preferences\receipts.ftl
sed -i -e 's/receipt-return-some-radio/receipt-return-some-radio-control/'   localization\zh-CN\messenger\preferences\receipts.ftl
sed -i -e 's/receipt-not-to-cc/receipt-not-to-cc-label/'                     localization\zh-CN\messenger\preferences\receipts.ftl
sed -i -e 's/sender-outside-domain/sender-outside-domain-label/'             localization\zh-CN\messenger\preferences\receipts.ftl
sed -i -e 's/other-cases-label/other-cases-text-label/'                      localization\zh-CN\messenger\preferences\receipts.ftl
```

Sadly localisation is a mess since the TB localisation is a mess and different languages are at different stages as you can see comparing, for example, de.cmd to fr.cmd.

I noticed that the following is still missing from zh-CN, here copied from the French:
```
:: Fix more mess from bug 1753824.
%lecho% "attachment-bucket-count = { $count ->"  >> localization\fr\messenger\messengercompose\messengercompose.ftl
%lecho% "    [1]      { $count } pièce jointe"   >> localization\fr\messenger\messengercompose\messengercompose.ftl
%lecho% "    *[other] { $count } pièces jointes" >> localization\fr\messenger\messengercompose\messengercompose.ftl
%lecho% "}"                                      >> localization\fr\messenger\messengercompose\messengercompose.ftl
```
It's correct in German and Japanese in the respective language packs:
https://searchfox.org/l10n/source/de/mail/messenger/messengercompose/messengercompose.ftl#87
https://searchfox.org/l10n/source/ja/mail/messenger/messengercompose/messengercompose.ftl#77

Please let me know if you want to remove the unnecessary ones and add the missing ones or whether I should do that.

For which platform do you require the build, Windows or Linux?

**Comment by scruel** [comment]
`sed -i -e` block for zh-CN seems not exists in [i10n page](https://searchfox.org/l10n/), and have committed the missing part that you mentioned into this PR.

I am using both Windows and Linux~ 😆

**Comment by scruel** [comment]
@Betterbird some mistake I think for the path, I will correct it

**Comment by Betterbird** [comment]
Well, meanwhile I removed the unnecessary lines: https://github.com/Betterbird/thunderbird-patches/commit/64afe946fdfcb3ddf496e368474426b6c6ef8234

**Comment by Betterbird** [comment]
Don't worry, I'll do it.

**Comment by scruel** [comment]
> Don't worry, I'll do it.

ok~

**Comment by scruel** [comment]
> Don't worry, I'll do it.

https://github.com/scruel/thunderbird-patches/commit/56e68786c8858f9d976de7b2c8a5734d04237b20

**Comment by Betterbird** [comment]
Sorry, we'll use our fix. Also, dock-options-show-badge is already in the official translation:
https://searchfox.org/l10n/source/zh-CN/mail/messenger/preferences/dock-options.ftl#8

**Comment by scruel** [comment]
> Sorry, we'll use our fix. Also, dock-options-show-badge is already in the official translation: https://searchfox.org/l10n/source/zh-CN/mail/messenger/preferences/dock-options.ftl#8

Ok

**Comment by Betterbird** [comment]
Done: https://github.com/Betterbird/thunderbird-patches/commit/fab0a6bab812b08f177351d8b8166bc21a622724

**Comment by Betterbird** [comment]
@scruel: Can ypu please help with a translation for:
https://github.com/Betterbird/thunderbird-patches/blob/365ac5ba07f79ba33c738cfd1aa6e64c85389abf/91/bugs/297852-grouping-search-term.patch#L95

**Comment by scruel** [comment]
Ok, I will do it later

**Comment by Betterbird** [comment]
No need for a PR, just send the string via e-mail.

**Comment by Betterbird** [comment]
Thanks, done: https://github.com/Betterbird/thunderbird-patches/commit/7870bb26528a49133e0a443b0541fc23fbfb1a6c. Waiting for Dutch and Japanese.

**Pull request merged**
