### PR TITLE
Create hu.cmd

### LINKED ISSUE #8: Listing of languages supported and Hungarian language support
>### In which languages will Betterbird ship?
>
>Betterbird will ship in English, major European languages and Japanese. Thunderbird language packs do not work since Betterbird has additional strings. Drop us a line if your language isn't supported yet. 

https://betterbird.eu/faq/index.html

Can you please advise which languages it ships with? If not on the webpage above, on this repository's [README](https://github.com/Betterbird/thunderbird-patches#readme)?

It would be appreciated if Hungarian is supported as it currently is not.

Thank you

P.S. Thank you for fixing `Mail/message listing/thread pane needs more organization in 3 vertical pane view (column wrapping, etc)` and providing a heads-up at https://bugzilla.mozilla.org/show_bug.cgi?id=213945#c214.

### PR DESCRIPTION
**Pull request by ovari**
Closes #8

### CODE REVIEW

**Comment by ovari** [comment]
Is/Are there any other file/s that need updating to enable Hungarian? Thank you

**Comment by ovari** [comment]
If any more strings are added, can these strings please be added to the hu.cmd file as we do this using the browser? Thank you

**Comment by ovari** [comment]
Closes #8

**Comment by Betterbird** [comment]
I don't understand what has happened here. I'm sure I posted this comment on Friday, two days ago. Here it is again:

Thanks. Would you mind revising this a bit. The `| %icv%` is needed where the string is non-ASCII, so also here `\"Beszélgetés\">" >> chrome\hu\locale\hu\messenger\msgHdrViewOverlay.dtd` and here `\"Továbbítás módja\">" >> chrome\hu\locale\hu\messenger\msgHdrViewOverlay.dtd` and for the badge.

Enigmail translates "Decrypt to folder" here
https://gitlab.com/enigmail/enigmail/-/blob/master/lang/hu/enigmail.dtd#L115
as "Visszafejtés egy mappába" which is different from your translation.

Note that many locales are currently broken, see https://bugzilla.mozilla.org/show_bug.cgi?id=1728893, so unless this is fixed, we can't localise BB.

**Comment by ovari** [comment]
All your comments should be fixed now.

Yes, BB can't be localised at the moment; however, you can have the strings ready for when it can.

Thanks for your feedback.

**Comment by ovari** [comment]
> Note that many locales are currently broken, see https://bugzilla.mozilla.org/show_bug.cgi?id=1728893, so unless this is fixed, we can't localise BB.

The issue is `closed` with the status `resolved fixed`. Does that mean that BB can have localised? Thank you

**Comment by Betterbird** [comment]
Sorry, something wrong here. If I click on 
https://github.com/ovari/thunderbird-patches/pull/13/commits/3fc1535c26dc5997fdd43b1f319778222d4cae05
I get a 404 :-(

**Comment by Betterbird** [comment]
Sorry, but this is not correct:
```
%lecho% "<!ENTITY hdrOpenConversationButton1.label \"Beszélgetés\">" >> | %icv% chrome\hu\locale\hu\messenger\msgHdrViewOverlay.dtd
```
Needs to be `| %icv% >> `

**Comment by ovari** [comment]
I'm sorry for the mistake. Updated

**Comment by Betterbird** [comment]
If I click onto the links here
image
I get a 404.
If I copy the link
https://github.com/ovari/thunderbird-patches/pull/13/commits/8818370edc35c2041e331926ef06e353f4df0294
I can then click it. What's going on?

**Comment by ovari** [comment]
Don't know what is going on!?

**Pull request merged**
