### PR TITLE
Fix window activation

### LINKED ISSUE #202: Clicking the tray icon does not raise the window on Linux
This happens at least on KDE https://github.com/Betterbird/thunderbird-patches/issues/198#issuecomment-1712515855 , on MATE https://github.com/Betterbird/thunderbird-patches/issues/198#issuecomment-1712483412 , and on Gnome https://github.com/Betterbird/thunderbird-patches/issues/198#issuecomment-1712555247 , regardless of whether the window was previously minimized or not https://github.com/Betterbird/thunderbird-patches/issues/198#issuecomment-1712512456 .

According to Qt docs I remember once reading, functions like `gtk_windows_present()` don't work regardless of the library - probably because they use the same call that window managers ignore for sake of "focus steal prevention". The recommended solution from that same documentation is to create a child window (a simple messagebox will do fine) and then hide it a few milliseconds later (in my experience, 10 ms is enough, but any less might not be). That would raise the window on any window manager.

### PR DESCRIPTION
**Pull request by dark-penguin**
A workaround for a GTK limitation
Closes #202

### CODE REVIEW

**Comment by Betterbird** [comment]
You can't edit patches like this. If you remove one line and add two, the patch won't apply. You need to change the numbers in the hunk header as well. Anyway, we don't leave old code commented out.

I'll do you a build with your change.

**Comment by dark-penguin** [comment]
I actually wondered about that - what you can change in a patch and what you can't. :) Now I know.

**Comment by Betterbird** [comment]
Plus there are two gtk_window_present() calls in the code. One to just raise and one when bringing back from being minimised and hidden. Looks like you hit the latter one. I'll change both.

**Comment by dark-penguin** [comment]
Actually, I've found it in three files:
```
13-feature-linux-minimise-to-tray-fix-activate.patch
13-feature-linux-minimise-to-tray-restore-window.patch
13-feature-linux-minimise-to-tray.patch
```
But I don't know how are they applied, so it could turn out to be three calls.

**Comment by Betterbird** [comment]
Yes, the three files show the evolution of this functionality. Now it's all merged together here:
https://github.com/Betterbird/thunderbird-patches/blob/b54ab1cf3ae39de4ec81eb910d3317dafb26ab67/115/features/13-feature-linux-minimise-to-tray.patch#L320
(that's the line you changed)

**Pull request closed without merging**
